apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-dotnet-cli-image
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
      type: string
      description: url of the git repo for the code of deployment
    - name: git-revision
      type: string
      description: revision to be used from repo of the code for deployment
      default: "main"
  tasks:
    - name: clone-source
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: $(params.git-revision)
    - name: build-image
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: quay.io/pittar/dotnet-50-ef-ubi8:latest
        - name: DOCKERFILE
          value: ./Containerfile
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - clone-source
